# Generated by Django 4.1.13 on 2026-01-14 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='has_calculator',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='test',
            name='instructions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='test',
            name='option_type_numeric',
            field=models.BooleanField(default=False, help_text='If True, options are 1,2,3,4'),
        ),
    ]
