# Generated by Django 4.1.13 on 2026-01-14 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0010_examdetail_target_exam'),
        ('tests', '0002_test_has_calculator_test_instructions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='target_exam',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tests', to='master_data.targetexam'),
        ),
    ]
