# Generated by Django 4.1.13 on 2026-01-14 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0003_test_target_exam'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='total_marks',
            field=models.IntegerField(default=0),
        ),
    ]
