# Generated by Django 4.1.13 on 2026-01-15 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centres', '0001_initial'),
        ('tests', '0004_test_total_marks'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='centres',
            field=models.ManyToManyField(blank=True, related_name='tests', to='centres.centre'),
        ),
    ]
