# Generated by Django 4.1.13 on 2026-01-15 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0002_alter_section_options_remove_section_code_and_more'),
        ('tests', '0005_test_centres'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='allotted_sections',
            field=models.ManyToManyField(blank=True, related_name='allotted_tests', to='sections.section'),
        ),
    ]
