# Generated by Django 4.1.13 on 2026-01-15 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('centres', '0002_centre_email_centre_phone_number'),
        ('tests', '0006_test_allotted_sections'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestCentreAllotment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('access_code', models.CharField(blank=True, max_length=6, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('centre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_allotments', to='centres.centre')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='centre_allotments', to='tests.test')),
            ],
            options={
                'ordering': ['centre__name'],
                'unique_together': {('test', 'centre')},
            },
        ),
    ]
