# Generated by Django 4.1.13 on 2026-01-16 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0007_testcentreallotment'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcentreallotment',
            name='code_history',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
