# Generated by Django 4.1.13 on 2026-01-21 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0001_initial'),
        ('tests', '0008_testcentreallotment_code_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='packages.package'),
        ),
    ]
