# Generated by Django 4.1.13 on 2026-03-16 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0009_test_package'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcentreallotment',
            name='is_code_sent',
            field=models.BooleanField(default=False),
        ),
    ]
