# Generated by Django 4.1.13 on 2026-03-24 16:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tests', '0010_testcentreallotment_is_code_sent'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('responses', models.JSONField(default=dict)),
                ('submission_type', models.CharField(choices=[('MANUAL', 'Manual'), ('TIME_UP', 'Time Up'), ('VIOLATION', 'Violation Detection')], default='MANUAL', max_length=20)),
                ('time_spent', models.IntegerField(default=0, help_text='Total time spent in seconds')),
                ('score', models.FloatField(default=0.0)),
                ('is_finalized', models.BooleanField(default=False, help_text='Set to True when student manually submits')),
                ('allow_resume', models.BooleanField(default=False, help_text='Admin must set to True to allow student to resume an interrupted session')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_submissions', to=settings.AUTH_USER_MODEL)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='tests.test')),
            ],
            options={
                'ordering': ['-submitted_at'],
                'unique_together': {('test', 'student')},
            },
        ),
    ]
