# Generated by Django 4.1.13 on 2026-03-26 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0011_testsubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcentreallotment',
            name='was_sent',
            field=models.BooleanField(default=False),
        ),
    ]
