# Generated by Django 4.1.13 on 2026-04-14 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0040_mastersection_alter_homework_sections_and_more'),
        ('tests', '0013_test_is_result_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='allotted_sections',
            field=models.ManyToManyField(blank=True, related_name='allotted_tests', to='master_data.mastersection'),
        ),
    ]
