# Generated by Django 4.1.13 on 2026-04-24 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0014_alter_test_allotted_sections'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='allotted_sections',
        ),
    ]
