# Generated by Django 4.1.13 on 2026-04-24 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0048_classlevel_erp_id'),
        ('tests', '0015_remove_test_allotted_sections'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='target_exams',
            field=models.ManyToManyField(blank=True, related_name='tests', to='master_data.targetexam'),
        ),
        migrations.AlterField(
            model_name='test',
            name='target_exam',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tests_deprecated', to='master_data.targetexam'),
        ),
    ]
