# Generated by Django 4.1.13 on 2026-04-24 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0016_test_target_exams_alter_test_target_exam'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='target_exam',
        ),
    ]
