# Generated by Django 4.1.13 on 2026-05-18 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0054_examdetail_sessions_alter_examdetail_session'),
        ('tests', '0017_remove_test_target_exam'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='sessions',
            field=models.ManyToManyField(blank=True, related_name='tests_multi', to='master_data.session'),
        ),
        migrations.AlterField(
            model_name='test',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tests', to='master_data.session'),
        ),
    ]
