# Generated by Django 4.1.13 on 2026-06-01 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0055_examdetail_class_levels_alter_examdetail_class_level'),
        ('tests', '0018_test_sessions_alter_test_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='class_levels',
            field=models.ManyToManyField(blank=True, related_name='tests_multi', to='master_data.classlevel'),
        ),
        migrations.AlterField(
            model_name='test',
            name='class_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tests', to='master_data.classlevel'),
        ),
    ]
