# Generated by Django 4.1.13 on 2026-06-10 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0019_test_class_levels_alter_test_class_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='is_omr_based',
            field=models.BooleanField(default=False, help_text='If True, this is an OMR-based exam'),
        ),
        migrations.CreateModel(
            name='OMRFailedRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_enrollment', models.CharField(help_text='Enrollment number as read from the Excel sheet (may be wrong/unrecognised)', max_length=200)),
                ('raw_data', models.JSONField(default=dict, help_text="Raw row data: answers dict (f001/f002...) for raw OMR, or {'score': X} for score sheet")),
                ('sheet_type', models.CharField(choices=[('raw', 'Raw OMR'), ('score', 'Score Sheet')], default='score', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='failed_omr_records', to='tests.test')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
