# Generated by Django 4.1.13 on 2026-06-10 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0020_test_is_omr_based_omrfailedrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='omrfailedrecord',
            name='row_num',
            field=models.IntegerField(blank=True, help_text='Row number in the Excel sheet', null=True),
        ),
    ]
