# Generated by Django 4.1.13 on 2026-01-09 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_customuser_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='created_by',
        ),
        migrations.AddField(
            model_name='customuser',
            name='created_by_username',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
