# Generated by Django 4.1.13 on 2026-01-09 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_loginlog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loginlog',
            name='user',
        ),
        migrations.AddField(
            model_name='loginlog',
            name='user_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='loginlog',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
