# Generated by Django 4.1.13 on 2026-02-11 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_loginlog_user_loginlog_user_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grievance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=255)),
                ('student_id', models.CharField(blank=True, max_length=100, null=True)),
                ('subject', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('priority', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default='Medium', max_length=10)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Unassigned', 'Unassigned'), ('Assign', 'Assign'), ('Resolved', 'Resolved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('teacher_name', models.CharField(blank=True, max_length=255, null=True)),
                ('teacher_id', models.CharField(blank=True, max_length=100, null=True)),
                ('assign_date', models.DateTimeField(blank=True, null=True)),
                ('solved_date', models.DateTimeField(blank=True, null=True)),
                ('solution_description', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
