# Generated by Django 4.1.13 on 2026-02-17 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_studytask_notice'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='exam_section',
            field=models.CharField(blank=True, help_text="Exam section from ERP (e.g., 'jeee 2023')", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='omr_code',
            field=models.CharField(blank=True, help_text='OMR code from ERP', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='rm_code',
            field=models.CharField(blank=True, help_text='RM code from ERP', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='study_section',
            field=models.CharField(blank=True, help_text='Study section from ERP', max_length=255, null=True),
        ),
    ]
