# Generated by Django 4.1.13 on 2026-02-17 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_customuser_exam_section_customuser_omr_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='is_general',
            field=models.BooleanField(default=True, help_text='Visible to all students if True'),
        ),
        migrations.AddField(
            model_name='notice',
            name='targeted_section',
            field=models.CharField(blank=True, help_text="Target ERP exam section (e.g. 'jeee 2023')", max_length=255, null=True),
        ),
    ]
