# Generated by Django 4.1.13 on 2026-03-14 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_notice_is_general_notice_targeted_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='centre_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='centre_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='employee_id',
            field=models.CharField(blank=True, help_text='Official Employee ID from ERP (e.g., EMP...)', max_length=100, null=True),
        ),
    ]
