# Generated by Django 4.1.13 on 2026-03-24 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_customuser_centre_code_customuser_centre_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='admission_number',
            field=models.CharField(blank=True, help_text='Admission Number from ERP', max_length=100, null=True),
        ),
    ]
