# Generated by Django 4.1.13 on 2026-04-05 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_customuser_admission_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='erp_student_id',
            field=models.CharField(blank=True, help_text='The unique _id from the ERP system', max_length=100, null=True),
        ),
    ]
