# Generated by Django 4.1.13 on 2026-04-24 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0048_classlevel_erp_id'),
        ('api', '0013_customuser_erp_student_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='class_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='master_data.classlevel'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='master_data.session'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='target_exam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='master_data.targetexam'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('superadmin', 'Super Admin'), ('admin', 'Admin'), ('faculty', 'Faculty'), ('teacher', 'Teacher'), ('staff', 'Staff'), ('student', 'Student'), ('parent', 'Parent')], default='student', max_length=20),
        ),
    ]
