# Generated by Django 4.1.13 on 2026-05-11 16:29

import api.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_studentstudyplannerconfig_studentpsychometricprofile_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('page_view', 'Page View'), ('video_play', 'Video Play'), ('video_pause', 'Video Pause'), ('video_complete', 'Video Complete'), ('heartbeat', 'Heartbeat'), ('click', 'Click')], max_length=20)),
                ('path', models.CharField(help_text='The URL or section path', max_length=500)),
                ('metadata', api.models.SafeJSONField(blank=True, default=dict)),
                ('duration', models.IntegerField(default=0, help_text='Duration in seconds (for heartbeats or video watch time)')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
