# Generated by Django 4.1.13 on 2026-05-15 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_doubt'),
    ]

    operations = [
        migrations.AddField(
            model_name='doubt',
            name='chapter',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='doubt',
            name='topic',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
