# Generated by Django 4.1.13 on 2026-05-15 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_doubt_chapter_doubt_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='doubt',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='doubts/'),
        ),
        migrations.AddField(
            model_name='doubt',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='doubts/'),
        ),
        migrations.AddField(
            model_name='doubt',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='doubts/pdfs/'),
        ),
        migrations.AddField(
            model_name='doubt',
            name='voice_note',
            field=models.FileField(blank=True, null=True, upload_to='doubts/audio/'),
        ),
    ]
