# Generated by Django 4.1.13 on 2026-05-15 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_doubt_image2_doubt_image3_doubt_pdf_doubt_voice_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='doubt',
            name='assign_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doubt',
            name='teacher_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='doubt',
            name='teacher_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='doubt',
            name='status',
            field=models.CharField(choices=[('Unassigned', 'Unassigned'), ('Assign', 'Assign'), ('Resolved', 'Resolved'), ('Rejected', 'Rejected')], default='Unassigned', max_length=20),
        ),
    ]
