# Generated by Django 4.1.13 on 2026-05-15 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_doubt_assign_date_doubt_teacher_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='grievance',
            name='centre_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='grievance',
            name='centre_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
