# Generated by Django 4.1.13 on 2026-05-15 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_doubt_centre_code_doubt_centre_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='grievance',
            name='class_level',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='grievance',
            name='class_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
