# Generated by Django 4.1.13 on 2026-05-15 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_grievance_class_level_grievance_class_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grievance',
            name='class_level',
        ),
        migrations.RemoveField(
            model_name='grievance',
            name='class_name',
        ),
        migrations.AddField(
            model_name='grievance',
            name='student_class',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
