# Generated by Django 4.1.13 on 2026-05-16 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_remove_grievance_class_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doubt',
            name='reply_image',
            field=models.ImageField(blank=True, null=True, upload_to='doubts/replies/'),
        ),
        migrations.AddField(
            model_name='doubt',
            name='reply_image2',
            field=models.ImageField(blank=True, null=True, upload_to='doubts/replies/'),
        ),
        migrations.AddField(
            model_name='doubt',
            name='reply_image3',
            field=models.ImageField(blank=True, null=True, upload_to='doubts/replies/'),
        ),
        migrations.AddField(
            model_name='doubt',
            name='reply_pdf',
            field=models.FileField(blank=True, null=True, upload_to='doubts/replies/pdfs/'),
        ),
        migrations.AddField(
            model_name='doubt',
            name='reply_voice_note',
            field=models.FileField(blank=True, null=True, upload_to='doubts/replies/audio/'),
        ),
    ]
