# Generated by Django 4.1.13 on 2026-06-11 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_add_teacher_reply_assets'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='assigned_batch',
            field=models.CharField(blank=True, help_text='Assigned batch from ERP', max_length=255, null=True),
        ),
    ]
