# Generated by Django 4.1.13 on 2026-06-22 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_customuser_assigned_batch'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='exam_tag_name',
            field=models.CharField(blank=True, help_text="Exam Tag name from ERP (e.g. 'JEE 1 YEAR', 'NEET 2 YEAR') — plain text fallback", max_length=100, null=True),
        ),
    ]
