# Generated by Django 4.1.13 on 2026-07-14 15:41

import api.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_add_exam_tag_name_to_customuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_id', models.CharField(blank=True, max_length=100, null=True)),
                ('teacher_name', models.CharField(blank=True, max_length=255, null=True)),
                ('subject', models.CharField(blank=True, max_length=255, null=True)),
                ('date_of_class', models.DateField(blank=True, null=True)),
                ('responses', api.models.SafeJSONField(default=dict)),
                ('average_score', models.FloatField(default=0.0, help_text='Calculated out of 5 based on responses')),
                ('centre_code', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_feedbacks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
