# Generated by Django 4.1.13 on 2026-07-24 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_classfeedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='classfeedback',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='classfeedback',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
