# Generated by Django 4.1.13 on 2026-07-27 15:38

import api.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_classfeedback_end_time_classfeedback_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='exam_instances',
            field=api.models.SafeJSONField(blank=True, default=list, help_text="List of Exam Instance names (e.g. ['JEE 1 YEAR'])"),
        ),
    ]
