# Generated by Django 4.1.13 on 2026-07-27 15:53

import api.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_customuser_exam_instances'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='exam_instances',
            field=api.models.SafeJSONField(blank=True, default=list, help_text='List of exam instance names from ERP'),
        ),
    ]
