# Generated by Django 4.1.13 on 2026-08-06 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_alter_customuser_exam_instances'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='exam_instances',
        ),
        migrations.AddField(
            model_name='customuser',
            name='exam_instance_names',
            field=models.CharField(blank=True, help_text="Comma-separated exam instance names from ERP examSchema (e.g. 'JEE 1 YEAR,NEET 2 YEAR')", max_length=500, null=True),
        ),
    ]
