# Generated by Django 4.1.13 on 2026-08-26 19:56

import api.models
from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_remove_customuser_exam_instances_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DCStoppedRecord',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('student_name', models.CharField(max_length=255)),
                ('roll_no', models.CharField(blank=True, max_length=100, null=True)),
                ('batch', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(default='DC Stopped', max_length=50)),
                ('stopped_date', models.DateField(blank=True, null=True)),
                ('reason', models.CharField(blank=True, max_length=255, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('follow_up_status', models.CharField(default='In Counseling', max_length=100)),
                ('centre_name', models.CharField(blank=True, max_length=255, null=True)),
                ('recorded_by', models.CharField(blank=True, max_length=255, null=True)),
                ('verification_status', models.CharField(default='Pending', max_length=50)),
                ('is_verified', models.BooleanField(default=False)),
                ('verified_by', models.CharField(blank=True, max_length=255, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PTMMeetingRecord',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('student_name', models.CharField(max_length=255)),
                ('admission_number', models.CharField(blank=True, max_length=100, null=True)),
                ('parent_name', models.CharField(blank=True, max_length=255, null=True)),
                ('teacher_name', models.CharField(blank=True, max_length=255, null=True)),
                ('centre_name', models.CharField(default='Kolkata Main Centre', max_length=255)),
                ('ptm_date', models.DateField(blank=True, null=True)),
                ('discussion_remarks', models.TextField()),
                ('student_performance', models.CharField(default='Satisfactory', max_length=255)),
                ('issues_discussed', models.TextField(blank=True, null=True)),
                ('follow_up_required', models.BooleanField(default=True)),
                ('next_ptm_date', models.DateField(blank=True, null=True)),
                ('document_name', models.CharField(blank=True, max_length=255, null=True)),
                ('document_url', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('referred_by', models.CharField(max_length=255)),
                ('referral_source', models.CharField(default='Teacher', max_length=50)),
                ('referred_person', models.CharField(max_length=255)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('interested_course', models.CharField(blank=True, max_length=255, null=True)),
                ('centre_name', models.CharField(blank=True, max_length=255, null=True)),
                ('referral_date', models.DateField(blank=True, null=True)),
                ('follow_up_status', models.CharField(default='New Referral', max_length=100)),
                ('conversion_status', models.CharField(default='In Progress', max_length=100)),
                ('reward_points', models.IntegerField(default=0)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TeacherTrainingRecord',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('teacher_name', models.CharField(max_length=255)),
                ('training_topic', models.CharField(max_length=255)),
                ('trainer', models.CharField(max_length=255)),
                ('training_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(default='Pending', max_length=50)),
                ('completion_date', models.CharField(default='Pending', max_length=50)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='classfeedback',
            name='chapter_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='classfeedback',
            name='entry_time',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='classfeedback',
            name='exit_time',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='classfeedback',
            name='topics',
            field=api.models.SafeJSONField(default=list),
        ),
    ]
