# Generated by Django 4.1.13 on 2026-01-14 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0004_test_total_marks'),
        ('sections', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='section',
            options={'ordering': ['priority', 'created_at']},
        ),
        migrations.RemoveField(
            model_name='section',
            name='code',
        ),
        migrations.AddField(
            model_name='section',
            name='allowed_questions',
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name='section',
            name='correct_marks',
            field=models.FloatField(default=4.0),
        ),
        migrations.AddField(
            model_name='section',
            name='negative_marks',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='section',
            name='partial_marks',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='section',
            name='partial_type',
            field=models.CharField(default='regular', max_length=50),
        ),
        migrations.AddField(
            model_name='section',
            name='priority',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='section',
            name='shuffle',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='section',
            name='subject_code',
            field=models.CharField(default='GEN', max_length=50),
        ),
        migrations.AddField(
            model_name='section',
            name='test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='tests.test'),
        ),
        migrations.AddField(
            model_name='section',
            name='total_questions',
            field=models.IntegerField(default=20),
        ),
    ]
