# Generated by Django 4.1.13 on 2026-01-20 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0010_remove_question_options_question_question_options'),
        ('sections', '0002_alter_section_options_remove_section_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='questions',
            field=models.ManyToManyField(blank=True, related_name='assigned_sections', to='questions.question'),
        ),
    ]
