# Generated by Django 4.1.13 on 2026-03-24 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0003_section_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='question_order',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
