# Generated by Django 4.1.13 on 2026-06-06 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0056_partialmarkrule_mastersection_partial_mark_rule'),
        ('sections', '0004_section_question_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='partial_mark_rule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='master_data.partialmarkrule'),
        ),
    ]
