# Generated by Django 4.1.13 on 2026-06-06 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0005_section_partial_mark_rule'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='question_type',
            field=models.CharField(default='SINGLE_CHOICE', max_length=50),
        ),
    ]
