# Generated by Django 4.1.13 on 2026-01-21 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0003_section_questions'),
        ('packages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='allotted_sections',
            field=models.ManyToManyField(blank=True, related_name='allotted_packages', to='sections.section'),
        ),
    ]
