# Generated by Django 4.1.13 on 2026-02-02 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0002_package_allotted_sections'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
    ]
