# Generated by Django 4.1.13 on 2026-04-24 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0003_package_is_published'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='allotted_sections',
        ),
    ]
