# Generated by Django 4.1.13 on 2026-08-05 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chapter_tests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chaptertestresult',
            name='question_data',
            field=models.JSONField(default=list, help_text='Snapshot of the questions'),
        ),
    ]
