# Generated by Django 4.1.13 on 2026-08-06 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chapter_tests', '0002_chaptertestresult_question_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chaptertestresult',
            name='score',
            field=models.FloatField(default=0.0),
        ),
    ]
