# Generated by Django 4.1.13 on 2026-09-28 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chapter_tests', '0003_alter_chaptertestresult_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='chaptertestresult',
            name='reflections',
            field=models.JSONField(blank=True, default=dict, help_text='Mistake reflections per question'),
        ),
    ]
