# Generated by Django 4.1.13 on 2026-01-15 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centres', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='centre',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='centre',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
