# Generated by Django 4.1.13 on 2026-01-14 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0002_examdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='examdetail',
            name='name',
            field=models.CharField(default='', help_text='Exam Title', max_length=255),
        ),
    ]
