# Generated by Django 4.1.13 on 2026-01-14 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0003_examdetail_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='examdetail',
            name='code',
            field=models.CharField(default='', help_text='Exam Code', max_length=100),
        ),
    ]
