# Generated by Django 4.1.13 on 2026-01-14 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0004_examdetail_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='examtype',
            name='target_exam',
            field=models.CharField(default='', help_text='e.g. JEE, NEET, WBJEE', max_length=100),
        ),
        migrations.AlterField(
            model_name='classlevel',
            name='code',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='examtype',
            name='code',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='code',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
