# Generated by Django 4.1.13 on 2026-01-14 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0006_targetexam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examtype',
            name='target_exam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exam_types', to='master_data.targetexam'),
        ),
    ]
