# Generated by Django 4.1.13 on 2026-01-14 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0007_alter_examtype_target_exam'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examtype',
            name='target_exam',
        ),
    ]
