# Generated by Django 4.1.13 on 2026-01-14 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0009_examtype_target_exam'),
    ]

    operations = [
        migrations.AddField(
            model_name='examdetail',
            name='target_exam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exam_details', to='master_data.targetexam'),
        ),
    ]
