# Generated by Django 4.1.13 on 2026-01-22 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0015_remove_topic_sub_topic_subtopic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chapter',
            old_name='order',
            new_name='sort_order',
        ),
        migrations.RenameField(
            model_name='subtopic',
            old_name='order',
            new_name='sort_order',
        ),
        migrations.RenameField(
            model_name='topic',
            old_name='order',
            new_name='sort_order',
        ),
    ]
