# Generated by Django 4.1.13 on 2026-02-02 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0003_section_questions'),
        ('master_data', '0018_libraryitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolutionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='solutions/thumbnails/')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='solutions/pdfs/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sections', models.ManyToManyField(blank=True, related_name='solutions', to='sections.section')),
            ],
        ),
    ]
