# Generated by Django 4.1.13 on 2026-02-03 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0019_solutionitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='solutionitem',
            name='answer_pdf',
            field=models.FileField(blank=True, null=True, upload_to='solutions/pdfs/answers/'),
        ),
        migrations.AddField(
            model_name='solutionitem',
            name='answer_thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='solutions/thumbnails/answers/'),
        ),
        migrations.AddField(
            model_name='solutionitem',
            name='answer_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='solutionitem',
            name='class_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solutions', to='master_data.classlevel'),
        ),
        migrations.AddField(
            model_name='solutionitem',
            name='exam_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solutions', to='master_data.examtype'),
        ),
        migrations.AddField(
            model_name='solutionitem',
            name='other_resource_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='solutionitem',
            name='question_pdf',
            field=models.FileField(blank=True, null=True, upload_to='solutions/pdfs/questions/'),
        ),
        migrations.AddField(
            model_name='solutionitem',
            name='question_thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='solutions/thumbnails/questions/'),
        ),
        migrations.AddField(
            model_name='solutionitem',
            name='question_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='solutionitem',
            name='resource_type_dpp',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='solutionitem',
            name='resource_type_others',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='solutionitem',
            name='resource_type_rpp',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='solutionitem',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solutions', to='master_data.session'),
        ),
        migrations.AddField(
            model_name='solutionitem',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solutions', to='master_data.subject'),
        ),
        migrations.AddField(
            model_name='solutionitem',
            name='target_exam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solutions', to='master_data.targetexam'),
        ),
    ]
