# Generated by Django 4.1.13 on 2026-02-03 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0021_notice'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='class_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notices', to='master_data.classlevel'),
        ),
        migrations.AddField(
            model_name='notice',
            name='exam_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notices', to='master_data.examtype'),
        ),
        migrations.AddField(
            model_name='notice',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notices', to='master_data.session'),
        ),
        migrations.AddField(
            model_name='notice',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notices', to='master_data.subject'),
        ),
        migrations.AddField(
            model_name='notice',
            name='target_exam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notices', to='master_data.targetexam'),
        ),
    ]
