# Generated by Django 4.1.13 on 2026-02-03 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0003_section_questions'),
        ('master_data', '0023_libraryitem_class_level_libraryitem_exam_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='libraryitem',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='library_items', to='sections.section'),
        ),
        migrations.AddField(
            model_name='notice',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notices', to='sections.section'),
        ),
    ]
