# Generated by Django 4.1.13 on 2026-02-03 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0003_package_is_published'),
        ('master_data', '0025_liveclass'),
    ]

    operations = [
        migrations.AddField(
            model_name='liveclass',
            name='is_general',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='liveclass',
            name='packages',
            field=models.ManyToManyField(blank=True, related_name='live_classes', to='packages.package'),
        ),
    ]
