# Generated by Django 4.1.13 on 2026-02-04 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0003_package_is_published'),
        ('sections', '0003_section_questions'),
        ('master_data', '0027_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='PenPaperTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(blank=True, max_length=100, unique=True)),
                ('duration', models.IntegerField(default=180, help_text='Duration in minutes')),
                ('test_type', models.CharField(default='Practice Paper', max_length=100)),
                ('pdf_link', models.URLField(help_text='Link to the Question Paper PDF', max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('show_solution', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_general', models.BooleanField(default=False)),
                ('class_level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pen_paper_tests', to='master_data.classlevel')),
                ('exam_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pen_paper_tests', to='master_data.examtype')),
                ('packages', models.ManyToManyField(blank=True, related_name='pen_paper_tests', to='packages.package')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pen_paper_tests', to='sections.section')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pen_paper_tests', to='master_data.session')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pen_paper_tests', to='master_data.subject')),
                ('target_exam', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pen_paper_tests', to='master_data.targetexam')),
            ],
        ),
    ]
