# Generated by Django 4.1.13 on 2026-02-04 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0028_penpapertest'),
    ]

    operations = [
        migrations.AddField(
            model_name='penpapertest',
            name='end_date',
            field=models.DateTimeField(blank=True, help_text='Last joining Date and Time', null=True),
        ),
        migrations.AddField(
            model_name='penpapertest',
            name='question_paper',
            field=models.FileField(blank=True, null=True, upload_to='pen_paper_tests/questions/'),
        ),
        migrations.AddField(
            model_name='penpapertest',
            name='solution_file',
            field=models.FileField(blank=True, null=True, upload_to='pen_paper_tests/solutions/'),
        ),
        migrations.AddField(
            model_name='penpapertest',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='penpapertest',
            name='pdf_link',
            field=models.URLField(blank=True, help_text='Link to the Question Paper PDF', max_length=500, null=True),
        ),
    ]
