# Generated by Django 4.1.13 on 2026-02-04 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0029_penpapertest_end_date_penpapertest_question_paper_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='penpapertest',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='Optional thumbnail image', null=True, upload_to='pen_paper_tests/thumbnails/'),
        ),
    ]
