# Generated by Django 4.1.13 on 2026-02-10 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0003_package_is_published'),
        ('master_data', '0031_homework'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='is_general',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='homework',
            name='packages',
            field=models.ManyToManyField(blank=True, related_name='homeworks', to='packages.package'),
        ),
    ]
