# Generated by Django 4.1.13 on 2026-02-10 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0003_section_questions'),
        ('master_data', '0032_homework_is_general_homework_packages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='penpapertest',
            name='section',
        ),
        migrations.AddField(
            model_name='penpapertest',
            name='sections',
            field=models.ManyToManyField(blank=True, related_name='pen_paper_tests', to='sections.section'),
        ),
    ]
