# Generated by Django 4.1.13 on 2026-02-10 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0035_seminar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content_type', models.CharField(choices=[('pdf', 'PDF'), ('video', 'Video')], max_length=10)),
                ('thumbnail', models.ImageField(upload_to='guides/thumbnails/')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='guides/pdfs/')),
                ('video_link', models.URLField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
