# Generated by Django 4.1.13 on 2026-02-10 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0037_community'),
    ]

    operations = [
        migrations.AddField(
            model_name='seminar',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
