# Generated by Django 4.1.13 on 2026-03-16 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0038_seminar_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examtype',
            name='target_exam',
        ),
        migrations.AddField(
            model_name='examtype',
            name='target_exams',
            field=models.ManyToManyField(blank=True, related_name='exam_types', to='master_data.targetexam'),
        ),
        migrations.AddField(
            model_name='libraryitem',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='library/videos/'),
        ),
        migrations.AddField(
            model_name='libraryitem',
            name='video_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='examdetail',
            name='code',
            field=models.CharField(blank=True, help_text='Exam Code', max_length=100, unique=True),
        ),
    ]
