# Generated by Django 4.1.13 on 2026-04-14 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0039_remove_examtype_target_exam_examtype_target_exams_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('subject_code', models.CharField(default='GEN', max_length=50)),
                ('total_questions', models.IntegerField(default=20)),
                ('allowed_questions', models.IntegerField(default=20)),
                ('shuffle', models.BooleanField(default=False)),
                ('correct_marks', models.FloatField(default=4.0)),
                ('negative_marks', models.FloatField(default=1.0)),
                ('partial_type', models.CharField(default='regular', max_length=50)),
                ('partial_marks', models.FloatField(default=0.0)),
                ('priority', models.IntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Master Section',
                'verbose_name_plural': 'Master Sections',
                'ordering': ['priority', 'created_at'],
            },
        ),
        migrations.AlterField(
            model_name='homework',
            name='sections',
            field=models.ManyToManyField(blank=True, related_name='homeworks', to='master_data.mastersection'),
        ),
        migrations.AlterField(
            model_name='libraryitem',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='library_items', to='master_data.mastersection'),
        ),
        migrations.AlterField(
            model_name='liveclass',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='live_classes', to='master_data.mastersection'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notices', to='master_data.mastersection'),
        ),
        migrations.AlterField(
            model_name='penpapertest',
            name='sections',
            field=models.ManyToManyField(blank=True, related_name='pen_paper_tests', to='master_data.mastersection'),
        ),
        migrations.AlterField(
            model_name='solutionitem',
            name='sections',
            field=models.ManyToManyField(blank=True, related_name='solutions', to='master_data.mastersection'),
        ),
        migrations.AlterField(
            model_name='video',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='videos', to='master_data.mastersection'),
        ),
    ]
