# Generated by Django 4.1.13 on 2026-04-16 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0040_mastersection_alter_homework_sections_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='libraryitem',
            name='chapter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='library_items', to='master_data.chapter'),
        ),
        migrations.AddField(
            model_name='libraryitem',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='library_items', to='master_data.topic'),
        ),
    ]
