# Generated by Django 4.1.13 on 2026-04-16 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0041_libraryitem_chapter_libraryitem_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='libraryitem',
            name='dpp_file',
            field=models.FileField(blank=True, null=True, upload_to='library/dpps/'),
        ),
    ]
