# Generated by Django 4.1.13 on 2026-04-16 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0012_question_chapter_question_solve_time'),
        ('master_data', '0042_libraryitem_dpp_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='libraryitem',
            name='questions',
            field=models.ManyToManyField(blank=True, related_name='library_items', to='questions.question'),
        ),
    ]
