# Generated by Django 4.1.13 on 2026-04-16 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0043_libraryitem_questions'),
    ]

    operations = [
        migrations.CreateModel(
            name='LibraryVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Optional title for this specific video', max_length=255, null=True)),
                ('video_link', models.URLField(blank=True, max_length=500, null=True)),
                ('video_file', models.FileField(blank=True, null=True, upload_to='library/videos_multi/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('library_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='master_data.libraryitem')),
            ],
        ),
        migrations.CreateModel(
            name='LibraryPDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Optional title for this specific PDF', max_length=255, null=True)),
                ('file', models.FileField(upload_to='library/pdfs_multi/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('library_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pdfs', to='master_data.libraryitem')),
            ],
        ),
    ]
