# Generated by Django 4.1.13 on 2026-04-24 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0044_libraryvideo_librarypdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='librarypdf',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='librarypdf',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='library/pdfs_thumbs/'),
        ),
        migrations.AddField(
            model_name='libraryvideo',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='libraryvideo',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='library/videos_thumbs/'),
        ),
        migrations.AddField(
            model_name='targetexam',
            name='erp_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='librarypdf',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='library/pdfs_multi/'),
        ),
        migrations.CreateModel(
            name='LibraryDPP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='library/dpps_multi/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='library/dpps_thumbs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('library_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dpps', to='master_data.libraryitem')),
            ],
        ),
    ]
