# Generated by Django 4.1.13 on 2026-04-24 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0048_classlevel_erp_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='examdetail',
            name='target_exams',
            field=models.ManyToManyField(blank=True, related_name='exam_details', to='master_data.targetexam'),
        ),
        migrations.AlterField(
            model_name='examdetail',
            name='target_exam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exam_details_deprecated', to='master_data.targetexam'),
        ),
    ]
