# Generated by Django 4.1.13 on 2026-04-24 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0049_examdetail_target_exams_alter_examdetail_target_exam'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examdetail',
            name='target_exam',
        ),
    ]
