# Generated by Django 4.1.13 on 2026-04-25 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0050_remove_examdetail_target_exam'),
    ]

    operations = [
        migrations.AddField(
            model_name='examdetail',
            name='has_calculator',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='examdetail',
            name='instructions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='examdetail',
            name='option_type_numeric',
            field=models.BooleanField(default=False),
        ),
    ]
