# Generated by Django 4.1.13 on 2026-04-30 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0052_homework_sessions_libraryitem_sessions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='target_exams',
            field=models.ManyToManyField(blank=True, related_name='homeworks_multi', to='master_data.targetexam'),
        ),
        migrations.AddField(
            model_name='libraryitem',
            name='target_exams',
            field=models.ManyToManyField(blank=True, related_name='library_items_multi', to='master_data.targetexam'),
        ),
        migrations.AddField(
            model_name='liveclass',
            name='target_exams',
            field=models.ManyToManyField(blank=True, related_name='live_classes_multi', to='master_data.targetexam'),
        ),
        migrations.AddField(
            model_name='notice',
            name='target_exams',
            field=models.ManyToManyField(blank=True, related_name='notices_multi', to='master_data.targetexam'),
        ),
        migrations.AddField(
            model_name='penpapertest',
            name='target_exams',
            field=models.ManyToManyField(blank=True, related_name='pen_paper_tests_multi', to='master_data.targetexam'),
        ),
        migrations.AddField(
            model_name='solutionitem',
            name='target_exams',
            field=models.ManyToManyField(blank=True, related_name='solutions_multi', to='master_data.targetexam'),
        ),
        migrations.AddField(
            model_name='video',
            name='target_exams',
            field=models.ManyToManyField(blank=True, related_name='videos_multi', to='master_data.targetexam'),
        ),
    ]
