# Generated by Django 4.1.13 on 2026-05-18 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0053_homework_target_exams_libraryitem_target_exams_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='examdetail',
            name='sessions',
            field=models.ManyToManyField(blank=True, related_name='exam_details_multi', to='master_data.session'),
        ),
        migrations.AlterField(
            model_name='examdetail',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exam_details', to='master_data.session'),
        ),
    ]
