# Generated by Django 4.1.13 on 2026-06-01 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0054_examdetail_sessions_alter_examdetail_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='examdetail',
            name='class_levels',
            field=models.ManyToManyField(blank=True, related_name='exam_details_multi', to='master_data.classlevel'),
        ),
        migrations.AlterField(
            model_name='examdetail',
            name='class_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exam_details', to='master_data.classlevel'),
        ),
    ]
