# Generated by Django 4.1.13 on 2026-06-06 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0055_examdetail_class_levels_alter_examdetail_class_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartialMarkRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(blank=True, max_length=50, unique=True)),
                ('logic_type', models.CharField(choices=[('STANDARD', 'Standard (No Partial)'), ('JEE_ADVANCED', 'JEE Advanced Step Marking'), ('WBJEE', 'WBJEE Fractional Marking'), ('CUSTOM_FRACTIONAL', 'Custom Fractional Marking')], default='STANDARD', max_length=50)),
                ('base_correct_marks', models.FloatField(default=4.0)),
                ('base_negative_marks', models.FloatField(default=1.0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exam_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partial_mark_rules', to='master_data.examtype')),
            ],
        ),
        migrations.AddField(
            model_name='mastersection',
            name='partial_mark_rule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='master_sections', to='master_data.partialmarkrule'),
        ),
    ]
