# Generated by Django 4.1.13 on 2026-07-17 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0058_mistakereason'),
    ]

    operations = [
        migrations.AddField(
            model_name='libraryitem',
            name='class_levels',
            field=models.ManyToManyField(blank=True, related_name='library_items_multi', to='master_data.classlevel'),
        ),
    ]
