# Generated by Django 4.1.13 on 2026-08-06 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0059_libraryitem_class_levels'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChapterTestSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('positive_marks', models.FloatField(default=1.0)),
                ('negative_marks', models.FloatField(default=0.0)),
            ],
            options={
                'verbose_name': 'Chapter Test Setting',
                'verbose_name_plural': 'Chapter Test Settings',
            },
        ),
    ]
