# Generated by Django 4.1.13 on 2026-01-16 13:58

from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master_data', '0013_topic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('SINGLE_CHOICE', 'SINGLE_CHOICE'), ('MULTI_CHOICE', 'MULTI_CHOICE'), ('MATRIX', 'MATRIX'), ('ASSERTION', 'ASSERTION'), ('INTEGER_TYPE', 'INTEGER_TYPE'), ('NUMERICAL', 'NUMERICAL'), ('PARAGRAPH', 'PARAGRAPH')], default='SINGLE_CHOICE', max_length=50)),
                ('level', models.CharField(default='1', max_length=10)),
                ('content', models.TextField(help_text='Rich text content')),
                ('solution', models.TextField(blank=True, help_text='Rich text solution', null=True)),
                ('options', models.JSONField(blank=True, default=list)),
                ('answer_from', models.FloatField(blank=True, null=True)),
                ('answer_to', models.FloatField(blank=True, null=True)),
                ('has_calculator', models.BooleanField(default=False)),
                ('use_numeric_options', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('class_level', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='master_data.classlevel')),
                ('exam_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='master_data.examtype')),
                ('subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='master_data.subject')),
                ('target_exam', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='master_data.targetexam')),
                ('topic', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='master_data.topic')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
