# Generated by Django 4.1.13 on 2026-01-19 12:47

from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0013_topic'),
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='image_1',
            field=models.TextField(blank=True, help_text='Primary image URL', null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='image_2',
            field=models.TextField(blank=True, help_text='Secondary image URL', null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='is_wrong',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='QuestionImage',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='question_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('class_level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='master_data.classlevel')),
                ('exam_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='master_data.examtype')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='master_data.subject')),
                ('target_exam', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='master_data.targetexam')),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='master_data.topic')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
