# Generated by Django 4.1.13 on 2026-01-19 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_question_image_1_question_image_2_question_is_wrong_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='level',
            field=models.CharField(db_column='difficulty_level', default='1', max_length=10),
        ),
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('SINGLE_CHOICE', 'SINGLE_CHOICE'), ('MULTI_CHOICE', 'MULTI_CHOICE'), ('MATRIX', 'MATRIX'), ('ASSERTION', 'ASSERTION'), ('INTEGER_TYPE', 'INTEGER_TYPE'), ('NUMERICAL', 'NUMERICAL'), ('PARAGRAPH', 'PARAGRAPH')], db_column='question_type', default='SINGLE_CHOICE', max_length=50),
        ),
    ]
