# Generated by Django 4.1.13 on 2026-01-19 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_alter_question_level_alter_question_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='level',
            new_name='q_level',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='type',
            new_name='q_type',
        ),
    ]
