# Generated by Django 4.1.13 on 2026-01-19 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_rename_level_question_q_level_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='content',
        ),
        migrations.RemoveField(
            model_name='question',
            name='options',
        ),
        migrations.RemoveField(
            model_name='question',
            name='solution',
        ),
        migrations.AddField(
            model_name='question',
            name='q_content',
            field=models.TextField(db_column='question_content', default='', help_text='Rich text content'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='q_options',
            field=models.JSONField(blank=True, db_column='question_options', default=list),
        ),
        migrations.AddField(
            model_name='question',
            name='q_solution',
            field=models.TextField(blank=True, db_column='question_solution', help_text='Rich text solution', null=True),
        ),
    ]
