# Generated by Django 4.1.13 on 2026-01-19 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_remove_question_content_remove_question_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='q_content',
        ),
        migrations.RemoveField(
            model_name='question',
            name='q_level',
        ),
        migrations.RemoveField(
            model_name='question',
            name='q_options',
        ),
        migrations.RemoveField(
            model_name='question',
            name='q_solution',
        ),
        migrations.RemoveField(
            model_name='question',
            name='q_type',
        ),
        migrations.AddField(
            model_name='question',
            name='content',
            field=models.TextField(blank=True, help_text='Rich text content', null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='level',
            field=models.CharField(default='1', max_length=10),
        ),
        migrations.AddField(
            model_name='question',
            name='options',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='question',
            name='solution',
            field=models.TextField(blank=True, help_text='Rich text solution', null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('SINGLE_CHOICE', 'SINGLE_CHOICE'), ('MULTI_CHOICE', 'MULTI_CHOICE'), ('MATRIX', 'MATRIX'), ('ASSERTION', 'ASSERTION'), ('INTEGER_TYPE', 'INTEGER_TYPE'), ('NUMERICAL', 'NUMERICAL'), ('PARAGRAPH', 'PARAGRAPH')], default='SINGLE_CHOICE', max_length=50),
        ),
        migrations.AlterField(
            model_name='question',
            name='is_wrong',
            field=models.BooleanField(default=False, help_text='Flag for incorrect questions'),
        ),
    ]
