# Generated by Django 4.1.13 on 2026-01-19 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0006_remove_question_q_content_remove_question_q_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='content',
            field=models.TextField(help_text='Rich text content'),
        ),
        migrations.AlterField(
            model_name='question',
            name='is_wrong',
            field=models.BooleanField(default=False),
        ),
    ]
