# Generated by Django 4.1.13 on 2026-01-20 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0008_rename_type_question_question_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='level',
            new_name='difficulty_level',
        ),
    ]
