# Generated by Django 4.1.13 on 2026-01-20 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0009_rename_level_question_difficulty_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='options',
        ),
        migrations.AddField(
            model_name='question',
            name='question_options',
            field=models.JSONField(blank=True, db_column='question_options', default=list),
        ),
    ]
