# Generated by Django 4.1.13 on 2026-03-24 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0039_remove_examtype_target_exam_examtype_target_exams_and_more'),
        ('questions', '0010_remove_question_options_question_question_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='test_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='master_data.examdetail'),
        ),
    ]
