# Generated by Django 4.1.13 on 2026-04-16 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0040_mastersection_alter_homework_sections_and_more'),
        ('questions', '0011_question_test_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='chapter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='master_data.chapter'),
        ),
        migrations.AddField(
            model_name='question',
            name='solve_time',
            field=models.IntegerField(default=60, help_text='Time to solve in seconds'),
        ),
    ]
